### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by Decopi** [ramkumar-kr/open-in-new-tab#4]
Hi,

Please, how can I use the wildcards with Facebook?

This add-on blocks many Facebook options (messages, friend requests, notifications, edit posts etc).
For many years I used https://addons.mozilla.org/en-US/firefox/addon/open-link-in-new-tab. It worked perfectly, but wasn't upgraded for FF+57. I look froward to replace it with your add-on. Please, help me with the wildcards.

Thank you again!

**Comment by ramkumar-kr** [comment]
Hi,

I just tested the extension with facebook and found out that links with href as "#" should not be altered.
I have released a beta version (https://addons.mozilla.org/en-US/firefox/addon/open-in-new-tab-domain/versions/beta?page=1#version-0.0.8beta1) which fixes this issue. I'll move this version from beta to official release after 2-3 weeks

**Comment by Decopi** [comment]
Hi @ramkumar-kr !

The beta version worked unblocking Facebook' options/links. Thank you!
The "Home", "Ownerpage" and "Settings" options/links even open in new tab! (before beta both were blocked).... that's great!!!!!!!!!!!!! Thank you again.

Options/links like "messages", "friends requests" and "notifications" as I said now are unblocked, however they still open in same tab. Please, It will be PERFECT if you can make them to open in new tab (the previous add-on I was using, it opened everything in new tab: https://addons.mozilla.org/en-US/firefox/addon/open-link-in-new-tab).

The facebook page was just a sample, for some links that were blocked or they just opened in same page. And my real request for you, PLEASE, is to make your add-on with the option to open all/every link in new tab. In simple words, if possible, I would like your add-on opening 100% of the links in every webpage (even blocked pages as https://addons.mozilla.org/en-US/firefox/), always all in new tab.

Thank you again!

**Comment by ramkumar-kr** [comment]
Hi,
Let us take Facebook as an example.
Links such as messages, notifications, friend requests do not have a URL associated with them. Without an URL, it would take a lot of time and effort to open them in a new tab and would require special code to be written specifically for facebook.com. Hence, I decided to stick to opening links without an URL in the same tab.

If you know about any other approach which doesn't involve writing code specifically for a website, you are welcome to raise a pull request and I will be glad to accept it.

Regarding opening blocked pages such as addons.mozilla.org, that won't be possible since it is a browser restriction.  You can read more about it in [https://bugzilla.mozilla.org/show_bug.cgi?id=1310082](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082)

**Comment by Decopi** [comment]
@ramkumar-kr Hi,

I don't have tech-info or know-how to explain how to open links without urls.
I only can present as a model, the legacy add-on I always used: https://addons.mozilla.org/en-US/firefox/addon/open-link-in-new-tab).

My guess as an ignorant, is that this my previous add-on is not working customizing each webpage. I believe that somehow, it works with a general code for all the webpages, allowing to open in new tabs most of the links (with/without urls). I say that because I used it for many years, and this add-on opened 95% of every link (with/without urls) in a new tab. Only "blocked" webpages (like mozilla.org) didn't work completely with this add-on (but some links opened in new tab!!!!!). It is still working perfectly in FF56.
My request to you, was based in this add-on.

But I don't want to take your time and attention.
Please, If my request is feasible, tell me what to do, I will open a "pull request" etc.
And if it is not feasible, please, feel free to close this issue.

Thanks!
